name: require_pod_antiaffinity
policies:
  - require_pod_antiaffinity.yaml
resources:
  - resource.yaml
results:
  - policy: require-pod-antiaffinity
    rule: require-either-hard-or-soft-antiaffinity
    resource: good-pod-required
    kind: Pod
    result: pass
  - policy: require-pod-antiaffinity
    rule: require-either-hard-or-soft-antiaffinity
    resource: good-pod-preferred
    kind: Pod
    result: pass
  - policy: require-pod-antiaffinity
    rule: require-either-hard-or-soft-antiaffinity
    resource: bad-pod-no-affinity
    kind: Pod
    result: fail
